config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :donations
  resources :request_donations
  
  get  'home/about'
  root 'home#index'
  #get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/donation.rb
class Donation < ApplicationRecord
	#belongs_to :request_donation, class_name: 'RequestDonation', foreign_key: 'request_donation_id'
  	belongs_to :request_donation, class_name: 'RequestDonation', foreign_key: 'request_donation_id'
    after_create :update_total_raised

  	def update_total_raised
    self.request_donation.total_raised += self.amount
    self.request_donation.save
  end
end

app/models/request_donation.rb
class RequestDonation < ApplicationRecord
	#set relationship with donations table
	 has_many :donations
	 after_initialize :set_default_total_raised, if: :new_record?

  	def set_default_total_raised
    	self.total_raised ||= 0
  	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_donation, only: %i[ show edit update destroy ]

  # GET /donations or /donations.json
  def index
    @donations = Donation.all
  end

  # GET /donations/1 or /donations/1.json
  def show
  end

  # GET /donations/new
  def new
    @donation = Donation.new
  end

  # GET /donations/1/edit
  def edit
  end

  # POST /donations or /donations.json
  def create
    @donation = Donation.new(donation_params)

    respond_to do |format|
      if @donation.save
        format.html { redirect_to donation_url(@donation), notice: "Donation was successfully created." }
        format.json { render :show, status: :created, location: @donation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donations/1 or /donations/1.json
  def update
    respond_to do |format|
      if @donation.update(donation_params)
        format.html { redirect_to donation_url(@donation), notice: "Donation was successfully updated." }
        format.json { render :show, status: :ok, location: @donation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1 or /donations/1.json
  def destroy
    @donation.destroy

    respond_to do |format|
      format.html { redirect_to donations_url, notice: "Donation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation = Donation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def donation_params
      #params.require(:donation).permit(:name, :campaign_ID, :amount, :comment)
      params.require(:donation).permit(:name, :campaign_ID, :amount, :comment,:request_donation_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end

  def donate
  end

  def request_donations
  end
end

app/controllers/request_donations_controller.rb
class RequestDonationsController < ApplicationController
  before_action :set_request_donation, only: %i[ show edit update destroy ]

  # GET /request_donations or /request_donations.json
  def index
    @request_donations = RequestDonation.all
  end

  # GET /request_donations/1 or /request_donations/1.json
  def show
  end

  # GET /request_donations/new
  def new
    @request_donation = RequestDonation.new
  end

  # GET /request_donations/1/edit
  def edit
  end

  # POST /request_donations or /request_donations.json
  def create
    @request_donation = RequestDonation.new(request_donation_params)

    respond_to do |format|
      if @request_donation.save
        format.html { redirect_to request_donation_url(@request_donation), notice: "Request donation was successfully created." }
        format.json { render :show, status: :created, location: @request_donation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @request_donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /request_donations/1 or /request_donations/1.json
  def update
    respond_to do |format|
      if @request_donation.update(request_donation_params)
        format.html { redirect_to request_donation_url(@request_donation), notice: "Request donation was successfully updated." }
        format.json { render :show, status: :ok, location: @request_donation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @request_donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /request_donations/1 or /request_donations/1.json
  def destroy
    # added this line to fix failure to delete
    # @request_donation = RequestDonation.find(params[:id]) #added
    @request_donation.destroy

    # redirect_to request_donation_path #new line

    respond_to do |format|
      format.html { redirect_to request_donations_url, notice: "Request donation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request_donation
      @request_donation = RequestDonation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def request_donation_params
      #params.require(:request_donation).permit(:campaign_name, :campaign_ID, :description, :target_amount, :total_raised, :campaign_enddate)
      params.require(:request_donation).permit(:campaign_name, :description, :target_amount, :total_raised, :campaign_enddate)

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/request_donations_helper.rb
module RequestDonationsHelper
end

app/views/donations/_donation.html.erb
<div id="<%= dom_id donation %>">
  <p>
    <strong>Name:</strong>
    <%= donation.name %>
  </p>

  <p>
    <strong>Campaign id:</strong>
    <%= donation.campaign_ID %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= donation.amount %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= donation.comment %>
  </p>

</div>

app/views/donations/_form.html.erb
<%= form_with(model: donation) do |form| %>
  <% if donation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
        <% donation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- #Added this code here -->
  <div class="field">
    <%= form.label :Campaign_Name, style: "display: block" %>
    <%= form.select :request_donation_id,  RequestDonation.all.map { |rd| [rd.campaign_name, rd.id] } %>
  </div>
  <br/>

<!-- format the form display -->
  <div>
    <%= form.text_field :name, class:"form-control", placeholder:" Your Name" %>
  </div>
<br/>


  <div>
    <%= form.number_field :amount, class:"form-control", placeholder:" Amount(Ksh)" %>
  </div>

<br/>
  <div>
    <%= form.text_field :comment, class:"form-control", placeholder:" Comment" %>
  </div>

<br/>

  <div>
    <%= form.submit  class:'btn btn-secondary'%>
  </div>
<% end %>

app/views/donations/edit.html.erb
<h1>Editing donation</h1>
<br/>
<%= render "form", donation: @donation %>

<br>

<div>
  <%= link_to "Show", @donation %> 
  <%= link_to "Back", donations_path %>
 
</div> 

app/views/donations/index.html.erb
<table class="table table-bordered table-hover">
  <thead class="table-secondary">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Amount</th>
      <th scope="col">Campaign_ID</th>
      <th scope="col">Comment</th>
      <th scope="col">Action</th>
    </tr>
  </thead>

<!-- <div id="donations"> -->
  <tbody>
  <% @donations.each do |donation| %>
    <!-- <%= render donation %> -->
    <tr>
      <td><%= donation.name %></td>
      <td><%= donation.amount %></td>
      <td><%= donation.request_donation_id %></td>
      <td><%= donation.comment %></td>
      <td>
         <%= link_to 'Show', donation_path(donation) %>
          <%= link_to 'Edit', edit_donation_path(donation) %>
          <%= link_to 'Delete', donation_path(donation), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
    </tr>
  </tbody>
  <% end %>
<!-- </div> -->
</table>
<%= link_to "New donation", new_donation_path, class:"btn btn-secondary" %>

app/views/donations/new.html.erb
<h1>New donation</h1>

<%= render "form", donation: @donation %>

<br>

<div>
  <%= link_to "Back to donations", donations_path %>
</div>

app/views/donations/show.html.erb
<%= render @donation %>

<div>
  <%= link_to "Edit", edit_donation_path(@donation), class:"btn btn-dark" %> 

  <%= link_to "Back", donations_path, class:"btn btn-secondary" %>
  <br> <br>
  <%= button_to "Delete", @donation, method: :delete, class:"btn btn-danger" %>

  
 
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
  <div class="container-fluid">
  	<%= link_to 'Crowdfund', root_path, class:"navbar-brand" %>
   
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
        	<%= link_to 'About Us', home_about_path, class:"nav-link active" %>
        </li>
     
            <li class="nav-item">
            	<%= link_to 'Donate', donations_path, class:"nav-link active" %>
            <li class="nav-item">
            	<%= link_to "Projects", request_donations_path, class:"nav-link active" %>
            </li>
            
          </ul>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<%= stylesheet_link_tag 'about' %>

  <div class="p-3 mb-2 bg-danger-subtle text-emphasis-danger", class="m-0">
  <h1> ABOUT US</h1>


  <h5><i>We love lending a helping hand<i></h5>

  <div class="row">
    <div class="col-md-6">
    	<%= image_tag("image-hero-mobile.jpg", alt:"...", class:"img-fluid") %>
    </div>
    <div class="col-md-6">
      <h2>Lorem</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
      <ul class="my-list">
	    <li>Item 1</li>
	    <li>Item 2</li>
	    <li>Item 3</li>
	    <li>Item 4</li>
	    <li>Item 5</li>
  	  </ul>
  	  <p> Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<%= stylesheet_link_tag 'about' %>

  <div class="p-3 mb-2 bg-danger-subtle text-emphasis-danger", class="m-0">
  <h1> HOME </h1>


  <h5><i>We love lending a helping hand<i></h5>

  <div class="row">
    <div class="col-md-6">
    	<%= image_tag("image-hero-mobile.jpg", alt:"...", class:"img-fluid") %>
    </div>
    <div class="col-md-6">
      <h2>Lorem</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
      <ul class="my-list">
	    <li>Item 1</li>
	    <li>Item 2</li>
	    <li>Item 3</li>
	    <li>Item 4</li>
	    <li>Item 5</li>
  	  </ul>
  	  <p> Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    </div>
  </div>
</div>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crowdfund</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'home/header' %>
    <div class="container">
    <% if notice %>
      <%= render 'layouts/alert' %>
    <% end %>
     
      <%= yield %>
  </div>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
  </body>
</html>

app/views/request_donations/_form.html.erb
<%= form_with(model: request_donation) do |form| %>
  <% if request_donation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(request_donation.errors.count, "error") %> prohibited this request_donation from being saved:</h2>

      <ul>
        <% request_donation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :campaign_name,  class:"form-control", placeholder:" Campaign name" %>
  </div>

<br/>
  <div>
    <%= form.text_field :description,  class:"form-control", placeholder:" Describe your campaign" %>
  </div>

<br/>
  <div>
    <%= form.number_field :target_amount,  class:"form-control", placeholder:"Enter Target Amount" %>
  </div>

<br/>
  <div>
    <%= form.label :campaign_enddate, style: "display: block" %>
    <%= form.date_field :campaign_enddate %>
  </div>

<br/>
  <div>
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/request_donations/_request_donation.html.erb
<div id="<%= dom_id request_donation %>">
  <p>
    <strong>Campaign name:</strong>
    <%= request_donation.campaign_name %>
  </p>

  <p>
    <strong>Campaign id:</strong>
    <%= request_donation.campaign_ID %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= request_donation.description %>
  </p>

  <p>
    <strong>Target amount:</strong>
    <%= request_donation.target_amount %>
  </p>

  <p>
    <strong>Total raised:</strong>
    <%= request_donation.total_raised %>
  </p>

  <p>
    <strong>Campaign enddate:</strong>
    <%= request_donation.campaign_enddate %>
  </p>

</div>

app/views/request_donations/edit.html.erb
<h1>Editing request donation</h1>

<%= render "form", request_donation: @request_donation %>

<br>

<div>
  <%= link_to "Show ", @request_donation %> |
  <%= link_to "Back to projects", request_donations_path %>
</div>

app/views/request_donations/index.html.erb
<table class="table table-bordered  table-hover">
 
   <thead class="table-secondary">
    <tr>
      <th scope="col">Campaign ID</th>
      <th scope="col">Campaign Name</th>
      <th scope="col">Description</th>
      <th scope="col">Target amount</th>
      <th scope="col">Total Raised</th>
      <th scope="col">Campaign end date</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody class="table-striped">
  <% @request_donations.each do |request_donation| %>
    <tr>
      <td><%= request_donation.id %></td>
      <td><%= request_donation.campaign_name %></td>
      <td><%= request_donation.description %></td>
      <td><%= request_donation.target_amount %></td>
      <td><%= request_donation.total_raised %></td>
      <td><%= request_donation.campaign_enddate %></td>
      <td>
         <%= link_to 'Show', request_donation_path(request_donation) %>

          <%= link_to 'Edit', edit_request_donation_path(request_donation) %>

          <%= button_to "Delete", request_donation_path(request_donation, confirm_delete: 'yes'), method: :delete, data: { confirm: "Are you sure?" } %>
        </td>
      </tr>
    </tbody>
      <% end %>
  </table>

<%= link_to "Request Donations",  new_request_donation_path, class:"btn btn-secondary" %>

app/views/request_donations/new.html.erb
<h2> New Campaign</h2>

<%= render "form", request_donation: @request_donation %>

<div>
  <%= link_to "Back to Campaigns", request_donations_path %>
</div>

app/views/request_donations/show.html.erb
<%= render @request_donation %>

<div>
    <br>
  <%= link_to "Edit ", edit_request_donation_path(@request_donation), class:"btn btn-dark" %> 
  <%= link_to "Back to projects", request_donations_path, class:"btn btn-secondary" %>

  <br>   <br> <%= button_to "Delete", @request_donation, method: :delete, class:"btn btn-danger" %>

  

  
</div>